services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - kafka-net

  broker:
    image: confluentinc/cp-kafka:7.3.0
    container_name: broker
    ports:
      - 19092:19092
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT_HOST://localhost:19092,PLAINTEXT_INTERNAL://broker:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL # Added this line
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    networks:
      - kafka-net

  scraper:
    build:
      context: ./scraper/cmd
      dockerfile: scraper.dockerfile
    container_name: scraper
    depends_on:
      - broker
    restart: always
    networks:
      - kafka-net

  store:
    build:
      context: ./store/cmd
      dockerfile: store.dockerfile
    container_name: store
    depends_on:
      - scraper
    restart: always
    networks:
      - kafka-net

  server:
    build:
     context: ./server/cmd
      dockerfile: server.dockerfile
    container_name: server
    ports:
      - 8080:8080
    depends_on:
      - store
    restart: always

    networks:
      - kafka-net

networks:
  kafka-net:
    driver: bridge
