version: "3"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - kafka-net

  broker:
    image: confluentinc/cp-kafka:7.3.0
    ports:
      - 19092:19092
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT_HOST://localhost:19092,PLAINTEXT_INTERNAL://broker:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL # Added this line
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    networks:
      - kafka-net

  scraper:
    image: mehulkumar27/gotrader_scraper:23551c1
    depends_on:
      - broker
    restart: always
    deploy:
      replicas: 2
      mode: replicated
      update_config:
        parallelism: 2
        delay: 2s
      restart_policy:
        condition: on-failure
    networks:
      - kafka-net

  store:
    image: mehulkumar27/gotrader_store:23551c1
    depends_on:
      - scraper
    restart: always
    deploy:
      replicas: 2
      mode: replicated
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 2
        delay: 2s
    networks:
      - kafka-net

  server:
    image: mehulkumar27/gotrader_server:23551c1
    container_name: server
    ports:
      - 8080:8080
    depends_on:
      - store
    restart: always
    deploy:
      replicas: 2
      mode: replicated
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 2
        delay: 2s
    networks:
      - kafka-net

networks:
  kafka-net:
    driver: overlay